{
    "docs": "https://docs.ansible.com/ansible-core/2.15/dev_guide/testing/sanity/import.html", 
    "results": [
        {
            "message": "The test `ansible-test sanity --test import --python 3.10` [[explain](https://docs.ansible.com/ansible-core/2.15/dev_guide/testing/sanity/import.html)] failed with 11 errors:", 
            "output": "plugins/module_utils/api_requests.py:9:0: traceback: ModuleNotFoundError: No module named 'requests'\nplugins/module_utils/cmd/cli.py:10:0: traceback: ModuleNotFoundError: No module named 'requests'\nplugins/module_utils/crypto.py:11:0: traceback: ModuleNotFoundError: No module named 'Crypto'\nplugins/module_utils/deploy/deploy.py:11:0: traceback: ModuleNotFoundError: No module named 'requests'\nplugins/module_utils/device_inventory/asa.py:10:0: traceback: ModuleNotFoundError: No module named 'requests'\nplugins/module_utils/device_inventory/delete.py:11:0: traceback: ModuleNotFoundError: No module named 'requests' (at plugins/module_utils/api_requests.py:9:0)\nplugins/module_utils/device_inventory/ftd.py:10:0: traceback: ModuleNotFoundError: No module named 'requests'\nplugins/module_utils/device_inventory/inventory.py:11:0: traceback: ModuleNotFoundError: No module named 'requests' (at plugins/module_utils/api_requests.py:9:0)\nplugins/modules/cmd.py:23:0: traceback: ModuleNotFoundError: No module named 'requests' (at plugins/module_utils/api_requests.py:9:0)\nplugins/modules/deploy.py:49:0: traceback: ModuleNotFoundError: No module named 'requests' (at plugins/module_utils/deploy/deploy.py:11:0)\nplugins/modules/device_inventory.py:204:0: traceback: ModuleNotFoundError: No module named 'requests' (at plugins/module_utils/api_requests.py:9:0)"
        }
    ], 
    "verified": false
}
